<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fidry_alice_data_fixtures.loader.simple' shared service.

return $this->services['fidry_alice_data_fixtures.loader.simple'] = new \Fidry\AliceDataFixtures\Loader\SimpleLoader(${($_ = isset($this->services['nelmio_alice.files_loader.simple']) ? $this->services['nelmio_alice.files_loader.simple'] : $this->load('getNelmioAlice_FilesLoader_SimpleService.php')) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : ($this->services['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())) && false ?: '_'});
