<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fidry_alice_data_fixtures.persistence.doctrine.purger.purger_factory' shared service.

return $this->services['fidry_alice_data_fixtures.persistence.doctrine.purger.purger_factory'] = new \Fidry\AliceDataFixtures\Bridge\Doctrine\Purger\Purger(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
