<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hgpestana.user.repository.user' shared service.

return $this->services['hgpestana.user.repository.user'] = new \HGPestana\UserBundle\Repository\UserRepository(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, 'HGPestana\\UserBundle\\Entity\\User');
