<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hautelook_alice.locator.environmentless' shared service.

return $this->services['hautelook_alice.locator.environmentless'] = new \Hautelook\AliceBundle\Locator\EnvironmentlessFilesLocator(${($_ = isset($this->services['hautelook_alice.locator.env_directory']) ? $this->services['hautelook_alice.locator.env_directory'] : $this->load('getHautelookAlice_Locator_EnvDirectoryService.php')) && false ?: '_'});
