<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hautelook_alice.data_fixtures.purge_loader' shared service.

return $this->services['hautelook_alice.data_fixtures.purge_loader'] = new \Fidry\AliceDataFixtures\Loader\FileResolverLoader(${($_ = isset($this->services['fidry_alice_data_fixtures.doctrine.purger_loader']) ? $this->services['fidry_alice_data_fixtures.doctrine.purger_loader'] : $this->load('getFidryAliceDataFixtures_Doctrine_PurgerLoaderService.php')) && false ?: '_'}, ${($_ = isset($this->services['hautelook_alice.resolver.file.kernel_file_resolver']) ? $this->services['hautelook_alice.resolver.file.kernel_file_resolver'] : ($this->services['hautelook_alice.resolver.file.kernel_file_resolver'] = new \Hautelook\AliceBundle\Resolver\File\KernelFileResolver(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'}))) && false ?: '_'});
