<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hautelook_alice.locator.env_directory' shared service.

return $this->services['hautelook_alice.locator.env_directory'] = new \Hautelook\AliceBundle\Locator\EnvDirectoryLocator($this->parameters['hautelook_alice.fixtures_path'], $this->getParameter('hautelook_alice.root_dirs'));
