<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_functional_test.services_database_backup.sqlite' shared service.

return $this->services['liip_functional_test.services_database_backup.sqlite'] = new \Liip\FunctionalTestBundle\Services\DatabaseBackup\SqliteDatabaseBackup($this, ${($_ = isset($this->services['liip_functional_test.services.fixtures_loader_factory']) ? $this->services['liip_functional_test.services.fixtures_loader_factory'] : ($this->services['liip_functional_test.services.fixtures_loader_factory'] = new \Liip\FunctionalTestBundle\Services\FixturesLoaderFactory($this, NULL))) && false ?: '_'});
