<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.file_parser.runtime_cache' shared service.

return $this->services['nelmio_alice.file_parser.runtime_cache'] = new \Nelmio\Alice\Parser\RuntimeCacheParser(${($_ = isset($this->services['nelmio_alice.file_parser.registry']) ? $this->services['nelmio_alice.file_parser.registry'] : $this->load('getNelmioAlice_FileParser_RegistryService.php')) && false ?: '_'}, ${($_ = isset($this->services['hautelook_alice.alice.file_locator.kernel']) ? $this->services['hautelook_alice.alice.file_locator.kernel'] : $this->load('getHautelookAlice_Alice_FileLocator_KernelService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.file_parser.default_include_processor']) ? $this->services['nelmio_alice.file_parser.default_include_processor'] : $this->load('getNelmioAlice_FileParser_DefaultIncludeProcessorService.php')) && false ?: '_'});
