<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.denormalizer.fixture.chainable.temporary_range' shared service.

return $this->services['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.temporary_range'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\Chainable\CollectionDenormalizerWithTemporaryFixture(${($_ = isset($this->services['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.null_range']) ? $this->services['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.null_range'] : ($this->services['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.null_range'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\Chainable\NullRangeNameDenormalizer())) && false ?: '_'});
