<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.file_parser.chainable.json' shared service.

return $this->services['nelmio_alice.file_parser.chainable.json'] = new \Nelmio\Alice\Parser\Chainable\JsonParser();
