<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.route_describers.fos_rest' shared service.

return $this->services['nelmio_api_doc.route_describers.fos_rest'] = new \Nelmio\ApiDocBundle\RouteDescriber\FosRestDescriber(${($_ = isset($this->services['annotation_reader']) ? $this->services['annotation_reader'] : $this->getAnnotationReaderService()) && false ?: '_'});
