<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.expression_language.lexer.empty_value_lexer' shared service.

return $this->services['nelmio_alice.fixture_builder.expression_language.lexer.empty_value_lexer'] = new \Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Lexer\EmptyValueLexer(${($_ = isset($this->services['nelmio_alice.fixture_builder.expression_language.lexer.reference_escaper_lexer']) ? $this->services['nelmio_alice.fixture_builder.expression_language.lexer.reference_escaper_lexer'] : $this->load('getNelmioAlice_FixtureBuilder_ExpressionLanguage_Lexer_ReferenceEscaperLexerService.php')) && false ?: '_'});
