<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.denormalizer.fixture.chainable.simple' shared service.

return $this->services['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.simple'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\Chainable\SimpleDenormalizer(${($_ = isset($this->services['nelmio_alice.fixture_builder.denormalizer.specs.simple']) ? $this->services['nelmio_alice.fixture_builder.denormalizer.specs.simple'] : $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_Specs_SimpleService.php')) && false ?: '_'});
