<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.value.chainable.unique_value_resolver' shared service.

return $this->services['nelmio_alice.generator.resolver.value.chainable.unique_value_resolver'] = new \Nelmio\Alice\Generator\Resolver\Value\Chainable\UniqueValueResolver(${($_ = isset($this->services['nelmio_alice.generator.resolver.value.unique_values_pool']) ? $this->services['nelmio_alice.generator.resolver.value.unique_values_pool'] : ($this->services['nelmio_alice.generator.resolver.value.unique_values_pool'] = new \Nelmio\Alice\Generator\Resolver\UniqueValuesPool())) && false ?: '_'}, NULL, 150);
