<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.guard.main' shared service.

return $this->services['security.authentication.provider.guard.main'] = new \Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider(new RewindableGenerator(function () {
    yield 0 => ${($_ = isset($this->services['hgpestana.user.authenticator.token']) ? $this->services['hgpestana.user.authenticator.token'] : $this->load('getHgpestana_User_Authenticator_TokenService.php')) && false ?: '_'};
}, 1), ${($_ = isset($this->services['hgpestana.user.api.provider']) ? $this->services['hgpestana.user.api.provider'] : $this->load('getHgpestana_User_Api_ProviderService.php')) && false ?: '_'}, 'main', new \Symfony\Component\Security\Core\User\UserChecker());
