language: php
sudo: false

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION="3.4.*"

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - SYMFONY_PHPUNIT_VERSION=5.7.27 ./vendor/bin/simple-phpunit

branches:
  only:
   - master

notifications:
  email:
    - hgpestana@gmail.com
