<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKfzzion\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKfzzion/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKfzzion.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKfzzion\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerKfzzion\appTestDebugProjectContainer([
    'container.build_hash' => 'Kfzzion',
    'container.build_id' => 'caeed484',
    'container.build_time' => 1558975182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKfzzion');
