<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.fixtures_load_command' shared service.

$this->services['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand(${($_ = isset($this->services['doctrine.fixtures.loader']) ? $this->services['doctrine.fixtures.loader'] : $this->load('getDoctrine_Fixtures_LoaderService.php')) && false ?: '_'});

$instance->setName('doctrine:fixtures:load');

return $instance;
