<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fidry_alice_data_fixtures.persistence.persister.doctrine.object_manager_persister' shared service.

return $this->services['fidry_alice_data_fixtures.persistence.persister.doctrine.object_manager_persister'] = new \Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
