<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fidry_alice_data_fixtures.doctrine.persister_loader' shared service.

return $this->services['fidry_alice_data_fixtures.doctrine.persister_loader'] = new \Fidry\AliceDataFixtures\Loader\PersisterLoader(${($_ = isset($this->services['fidry_alice_data_fixtures.loader.simple']) ? $this->services['fidry_alice_data_fixtures.loader.simple'] : $this->load('getFidryAliceDataFixtures_Loader_SimpleService.php')) && false ?: '_'}, ${($_ = isset($this->services['fidry_alice_data_fixtures.persistence.persister.doctrine.object_manager_persister']) ? $this->services['fidry_alice_data_fixtures.persistence.persister.doctrine.object_manager_persister'] : $this->load('getFidryAliceDataFixtures_Persistence_Persister_Doctrine_ObjectManagerPersisterService.php')) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : ($this->services['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())) && false ?: '_'}, []);
