<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fidry_alice_data_fixtures.loader.multipass_file' shared service.

@trigger_error('The service "fidry_alice_data_fixtures.loader.multipass_file" is deprecated and will be removed in future versions.', E_USER_DEPRECATED);

return $this->services['fidry_alice_data_fixtures.loader.multipass_file'] = new \Fidry\AliceDataFixtures\Loader\MultiPassLoader(${($_ = isset($this->services['nelmio_alice.file_loader.simple']) ? $this->services['nelmio_alice.file_loader.simple'] : $this->load('getNelmioAlice_FileLoader_SimpleService.php')) && false ?: '_'});
