<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hgpestana.user.authenticator.basic' shared service.

return $this->services['hgpestana.user.authenticator.basic'] = new \HGPestana\UserBundle\Security\Core\Authentication\BasicAuthenticator(${($_ = isset($this->services['hgpestana.user.repository.user']) ? $this->services['hgpestana.user.repository.user'] : $this->load('getHgpestana_User_Repository_UserService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.password_encoder']) ? $this->services['security.password_encoder'] : $this->load('getSecurity_PasswordEncoderService.php')) && false ?: '_'});
