<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hautelook_alice.loader.doctrine_orm_loader' shared service.

return $this->services['hautelook_alice.loader.doctrine_orm_loader'] = new \Hautelook\AliceBundle\Loader\DoctrineOrmLoader(${($_ = isset($this->services['hautelook_alice.resolver.bundle.no_bundle_resolver']) ? $this->services['hautelook_alice.resolver.bundle.no_bundle_resolver'] : $this->load('getHautelookAlice_Resolver_Bundle_NoBundleResolverService.php')) && false ?: '_'}, ${($_ = isset($this->services['hautelook_alice.locator.environmentless']) ? $this->services['hautelook_alice.locator.environmentless'] : $this->load('getHautelookAlice_Locator_EnvironmentlessService.php')) && false ?: '_'}, ${($_ = isset($this->services['hautelook_alice.data_fixtures.purge_loader']) ? $this->services['hautelook_alice.data_fixtures.purge_loader'] : $this->load('getHautelookAlice_DataFixtures_PurgeLoaderService.php')) && false ?: '_'}, ${($_ = isset($this->services['hautelook_alice.data_fixtures.append_loader']) ? $this->services['hautelook_alice.data_fixtures.append_loader'] : $this->load('getHautelookAlice_DataFixtures_AppendLoaderService.php')) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : ($this->services['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())) && false ?: '_'});
