<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hautelook_alice.resolver.file.kernel_file_resolver' shared service.

return $this->services['hautelook_alice.resolver.file.kernel_file_resolver'] = new \Hautelook\AliceBundle\Resolver\File\KernelFileResolver(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'});
