<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hautelook_alice.alice.file_locator.kernel' shared service.

return $this->services['hautelook_alice.alice.file_locator.kernel'] = new \Hautelook\AliceBundle\Alice\FileLocator\KernelFileLocator(${($_ = isset($this->services['nelmio_alice.file_locator.default']) ? $this->services['nelmio_alice.file_locator.default'] : ($this->services['nelmio_alice.file_locator.default'] = new \Nelmio\Alice\FileLocator\DefaultFileLocator())) && false ?: '_'}, ${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'});
