<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hgpestana.user.provider' shared service.

return $this->services['hgpestana.user.provider'] = new \HGPestana\UserBundle\Security\Core\Provider\UserProvider(${($_ = isset($this->services['hgpestana.user.repository.user']) ? $this->services['hgpestana.user.repository.user'] : $this->load('getHgpestana_User_Repository_UserService.php')) && false ?: '_'});
