<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hautelook_alice.alice.generator.instantiator.chainable.instantiated_reference_instantiator' shared service.

$this->services['hautelook_alice.alice.generator.instantiator.chainable.instantiated_reference_instantiator'] = $instance = new \Hautelook\AliceBundle\Alice\Generator\Instantiator\Chainable\InstantiatedReferenceInstantiator();

$instance->setContainer($this);

return $instance;
