<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hautelook_alice.console.command.doctrine.doctrine_orm_load_data_fixtures_command' shared service.

return $this->services['hautelook_alice.console.command.doctrine.doctrine_orm_load_data_fixtures_command'] = new \Hautelook\AliceBundle\Console\Command\Doctrine\DoctrineOrmLoadDataFixturesCommand('hautelook:fixtures:load', ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['hautelook_alice.loader.doctrine_orm_loader']) ? $this->services['hautelook_alice.loader.doctrine_orm_loader'] : $this->load('getHautelookAlice_Loader_DoctrineOrmLoaderService.php')) && false ?: '_'});
