<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_functional_test.services_database_backup.mysql' shared service.

return $this->services['liip_functional_test.services_database_backup.mysql'] = new \Liip\FunctionalTestBundle\Services\DatabaseBackup\MysqlDatabaseBackup($this, ${($_ = isset($this->services['liip_functional_test.services.fixtures_loader_factory']) ? $this->services['liip_functional_test.services.fixtures_loader_factory'] : $this->load('getLiipFunctionalTest_Services_FixturesLoaderFactoryService.php')) && false ?: '_'});
