<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_functional_test.services.fixtures_loader_factory' shared service.

return $this->services['liip_functional_test.services.fixtures_loader_factory'] = new \Liip\FunctionalTestBundle\Services\FixturesLoaderFactory($this, ${($_ = isset($this->services['doctrine.fixtures.loader']) ? $this->services['doctrine.fixtures.loader'] : $this->load('getDoctrine_Fixtures_LoaderService.php')) && false ?: '_'});
