<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_functional_test.services.database_tool_collection' shared service.

$this->services['liip_functional_test.services.database_tool_collection'] = $instance = new \Liip\FunctionalTestBundle\Services\DatabaseToolCollection($this, ${($_ = isset($this->services['annotations.reader']) ? $this->services['annotations.reader'] : $this->getAnnotations_ReaderService()) && false ?: '_'});

$a = ${($_ = isset($this->services['liip_functional_test.services.fixtures_loader_factory']) ? $this->services['liip_functional_test.services.fixtures_loader_factory'] : $this->load('getLiipFunctionalTest_Services_FixturesLoaderFactoryService.php')) && false ?: '_'};

$instance->add(new \Liip\FunctionalTestBundle\Services\DatabaseTools\ORMDatabaseTool($this, $a));
$instance->add(new \Liip\FunctionalTestBundle\Services\DatabaseTools\ORMSqliteDatabaseTool($this, $a));
$instance->add(new \Liip\FunctionalTestBundle\Services\DatabaseTools\MongoDBDatabaseTool($this, $a));
$instance->add(new \Liip\FunctionalTestBundle\Services\DatabaseTools\PHPCRDatabaseTool($this, $a));

return $instance;
