<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.value.chainable.parameter_value_resolver' shared service.

return $this->services['nelmio_alice.generator.resolver.value.chainable.parameter_value_resolver'] = new \Nelmio\Alice\Generator\Resolver\Value\Chainable\ParameterValueResolver();
