<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.hydrator.property.symfony_property_access' shared service.

return $this->services['nelmio_alice.generator.hydrator.property.symfony_property_access'] = new \Nelmio\Alice\Generator\Hydrator\Property\SymfonyPropertyAccessorHydrator(${($_ = isset($this->services['nelmio_alice.property_accessor.std']) ? $this->services['nelmio_alice.property_accessor.std'] : $this->load('getNelmioAlice_PropertyAccessor_StdService.php')) && false ?: '_'});
