<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.file_parser.default_include_processor' shared service.

return $this->services['nelmio_alice.file_parser.default_include_processor'] = new \Nelmio\Alice\Parser\IncludeProcessor\DefaultIncludeProcessor(${($_ = isset($this->services['hautelook_alice.alice.file_locator.kernel']) ? $this->services['hautelook_alice.alice.file_locator.kernel'] : $this->load('getHautelookAlice_Alice_FileLocator_KernelService.php')) && false ?: '_'});
