<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.caller.chainable.configurator_method_call' shared service.

return $this->services['nelmio_alice.generator.caller.chainable.configurator_method_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\ConfiguratorMethodCallProcessor();
